spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: khushal
    password: khushal
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

#        talked about in the video at 55 minutes or so

#      smtp:
#      trust: "*"
#      auth: true
#      starttls:
#        enable: true
#      connectiontimeout: 5000
#      timeout: 3000
#      writetimeout: 5000





application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

#spring.mail.properties.mail.smtp